### ISSUE TITLE
Test report is not generated 

### ISSUE THREAD

**Issue by calystoramesh** [rochejul/gulp-angular-protractor#15]
Hi, 

var gulp = require('gulp'),
    gulpProtractorAngular = require('gulp-angular-protractor');

// Setting up the test task
gulp.task('protractor-test', function(callback) {
    gulp
        .src(['/tests/*_/_.js'])
        .pipe(gulpProtractorAngular({
            'configFile': 'protractor.conf.js',
            'debug': false,
            'autoStartStopServer': true
        }))
        .on('error', function(e) {
            console.log(e);
        })
        .on('end', callback);
});

it's working fine but Test report is not generated .

note: without using GULP task then Test Report working fine .

**Comment by rochejul** [comment]
Hi

Can I have the cintent of your protractor.conf.js file please ?

Many thanks

**Comment by calystoramesh** [comment]
var appConfig = require(path.resolve(__dirname, 'configuration/appConfig.js'));

/*
 Load protractor config from the application configuration
 */

var protractorConfig = appConfig.get('protractorConfig');

/*
 Configure the reports from configuration
 */
protractorConfig.onPrepare = function () {

```
//region Execution Reporting:

return browser.getProcessedConfig()
    .then(function (config) {
        var browserName = config.capabilities.browserName;

        setGlobals(browserName);


        browser.driver.manage().window().maximize();//Making a Full Screen




        //protractor-jasmine2-html-reporter
        var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
        jasmine.getEnv().addReporter(new Jasmine2HtmlReporter({
            savePath: 'reports/' + browserName,
            screenshotsFolder: 'screenShots',
            takeScreenshots: true,
            takeScreenshotsOnlyOnFailures: false,
            fixedScreenshotName: true,
            filePrefix: 'Screen-report',
            consolidate: true,
            consolidateAll: true
        }));

        //Spec Reporter
        var SpecReporter = require('jasmine-spec-reporter');
        jasmine.getEnv().addReporter(new SpecReporter({displayStacktrace: true}));

        //Logger.info("jasmineReporters configuration is :", reportsConfig);
        //Logger.info("Enabling the reporter :%s . Configuration : %j ", reporterKey, reportsConfig[reporterKey]);
    });

//endregion
```

};

protractorConfig.suites = {
    //Test: data.loadSpecs('Test'),
    CRUD: data.loadSpecs('CRUD')
    //Smoke: data.loadSpecs('Smoke'),
    //Regression: data.loadSpecs('Regression')
};

```
};
```

exports.config = protractorConfig;

**Comment by rochejul** [comment]
Hi,

I remember an issue with Protractor and Jasmine2HtmlReporter when we need to create first all targeted folders to save the reports

When you run your gulp task, the folders are already created ? 
Can you give rerun your gulp task in verbose mode and give me your output ?

Many thanks

Cheers

**Comment by calystoramesh** [comment]
HI 
Protractor and Jasmine2HtmlReporter - working fine. command line mode protractor <conf.js)
When you run your gulp task, the folders are already created ? 
I checked both ways 
1.  with folder 
2. without folder 
no luck 
Can you give rerun your gulp task in verbose mode and give me your output ?
"C:\Program Files (x86)\JetBrains\WebStorm 2016.1.1\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\Rameshkumar.Balakris\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js --color --gulpfile c:\Users\Rameshkumar.Balakris\Documents\PsUiServer\ProtractorTests\gulpFile.js protractor-test 
[04:20:49] Using gulpfile c:\Users\Rameshkumar.Balakris\Documents\PsUiServer\ProtractorTests\gulpFile.js
[04:20:49] Starting 'protractor-test'...
[04:20:49] gulp-angular-protractor - The plugin is retrieved and will start soon
[04:20:49] gulp-angular-protractor - We will try to start and stop automatically the WebDriver server
[04:20:50] gulp-angular-protractor - The selenium address is: http://localhost:4444/wd/hub
[04:20:50] gulp-angular-protractor - The selenium address used is: http://localhost:4444/wd/hub
[04:20:50] gulp-angular-protractor - The selenium shutdown address used is: http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
[04:20:50] gulp-angular-protractor - We have the config file to the following path: c:\Users\Rameshkumar.Balakris\Documents\PsUiServer\ProtractorTests\protractor.conf.js
[04:20:50] gulp-angular-protractor - Webdriver standalone will be updated
selenium standalone is up to date.
chromedriver is up to date.
[04:20:51] gulp-angular-protractor - Webdriver standalone is updated
[04:20:51] gulp-angular-protractor - Webdriver standalone server will be started
[04:20:53] seleniumProcess.pid: 12804

[04:20:53] 04:20:53.407 INFO - Launching a standalone Selenium Server

[04:20:53] Setting system property webdriver.chrome.driver to c:\Users\Rameshkumar.Balakris\Documents\PsUiServer\ProtractorTests\node_modules\gulp-angular-protractor\node_modules\gulp-protractor\node_modules\protractor\selenium\chromedriver.exe

[04:20:53] 04:20:53.511 INFO - Java: Oracle Corporation 25.91-b15

[04:20:53] 04:20:53.512 INFO - OS: Windows 8.1 6.3 amd64

[04:20:53] 04:20:53.534 INFO - v2.48.0, with Core v2.48.0. Built from revision 41bccdd

[04:20:53] 04:20:53.675 INFO - Driver class not found: com.opera.core.systems.OperaDriver

[04:20:53] 04:20:53.676 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered

[04:20:53] 04:20:53.879 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub

[04:20:53] 04:20:53.880 INFO - Selenium Server is up and running

[04:20:53] gulp-angular-protractor - Webdriver standalone server is started
[04:20:53] gulp-angular-protractor - We will run the Protractor engine
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Spec started
Started
Login...
*
  AP -
    ✓ Verify that buttons should be disabled on the parent nav bar in search mode
.    ✓ Verify that buttons should be enable on the parent nav bar in search mode
.    ✓ Navigate to Add mode
.    ✓ Verify that buttons should be disabled on the parent nav bar in add mode
.    ✓ Verify that buttons should be enable on the parent nav bar in search mode
.\*    ✓ verify the error message should be shown when on saving the EMPTY record
.    ✓ verify the error message should be shown without value for Security Code when on saving the record
.    ✓ Verify that user able to add a new record
.    ✓ Verify that user is able to select the record
.    ✓ Verify that update the record
.    ✓ verify the record is not deleted
.    ✓ verify the record is deleted
.

---
-                    Pending                     *
  **************************************************

1) AP - Verify that page should be shown with search mode
  No reason given

2) AP: - Verify that Tab order
  No reason given

Executed 12 of 14 specs SUCCESS (2 PENDING) in 1 min 15 secs.

Pending:

1) AP- Verify that page should be shown with search mode
  No reason given

2) AP - Verify that Tab order
  No reason given

14 specs, 0 failures, 2 pending specs
Finished in 74.677 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chromeANY #1 passed
[04:22:16] 04:22:16.182 INFO - Command request: shutDownSeleniumServer[, ] on session null

[04:22:16] 04:22:16.183 INFO - Shutdown command received

[04:22:16] gulp-angular-protractor - Webdriver standalone server is stopped
[04:22:16] Finished 'protractor-test' after 1.43 min
[04:22:16] 04:22:16.184 INFO - Got result: OK on session null
04:22:16.184 INFO - initiating shutdown

[04:22:16] 04:22:16.686 INFO - Shutting down...

[04:22:16] Selenium Standalone has exited with code 0

[04:22:17] gulp-angular-protractor - Webdriver standalone server will be closed

NOTE: One more doubt : Possible to do the Direct support for suite argument
for example :
        args: [
            '--suite', args.suite
        ];

 running: protractor-test --suite myTest

**Comment by calystoramesh** [comment]
please help

**Comment by rochejul** [comment]
Do you really need to use "browser.getProcessedConfig()" ? Because I never use it and my "onPrepare" function looks like this:

``` js
// A callback function called once protractor is ready and available, and
// before the specs are executed
// You can specify a file containing code to run by setting onPrepare to
// the filename string.
onPrepare: function () {
    var fs = require('fs');
    !fs.existsSync(__dirname + '/target') &&  fs.mkdirSync(__dirname + '/target');
    !fs.existsSync(__dirname + '/target/e2e') &&  fs.mkdirSync(__dirname + '/target/e2e');

    require('jasmine-reporters');
    jasmine.getEnv().addReporter(
       new jasmine.JUnitXmlReporter(__dirname + '/target/e2e', true, true));
}
```

Can you try this please ?

Many thanks

**Comment by calystoramesh** [comment]
still I have an problem to generate the Test report as a XML format 

Finished in 19.013 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] phantomjs #1 passed
[05:39:58] 05:39:58.873 INFO - Command request: shutDownSeleniumServer[, ] on session null

[05:39:58] 05:39:58.874 INFO - Shutdown command received

[05:39:58] 05:39:58.875 INFO - initiating shutdown

[05:39:58] gulp-angular-protractor - Webdriver standalone server is stopped
[05:39:58] Finished 'protractor-test' after 30 s
[05:39:58] 'protractor-test' errored after 30 s
[05:39:58] Error: task completion callback called too many times
    at finish (node_modules\orchestrator\lib\runTask.js:15:10)
    at node_modules\orchestrator\lib\runTask.js:52:4
    at f (\node_modules\once\once.js:17:25)
    at Stream.onend (node_modules\end-of-stream\index.js:31:18)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at node_modules\gulp-angular-protractor\gulp-angular-protractor\gulp-stream.js:72:50
    at ClientRequest.<anonymous> (node_modules\gulp-angular-protractor\gulp-angular-protractor\web-driver.js:146:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
[05:39:58] 05:39:58.876 INFO - Got result: OK on session null

[05:39:59] Selenium Standalone has exited with code 0

[05:39:59] gulp-angular-protractor - Webdriver standalone server will be closed

Process finished with exit code 1

**Comment by calystoramesh** [comment]
really I am stuck up on this please give me some suggestion

**Comment by rochejul** [comment]
Hi

Maybe this a CWD issue (depends where you have launch your command). Can you remove the generated reports, launch the gulp task and search on your system a file with your report's name ? Maybe it is saved in another place ?

I have very few times to work on my side projects. I hope to check this on the next weeks

Cheers

**Comment by rochejul** [comment]
Weird: I push a third example with the JUnit report generation and it works fine: https://github.com/rochejul/gulp-angular-protractor/tree/master/examples/example-03

Can you clone the project, and test on your machine this example please ?

It seems a problem on your configuration

Cheers

**Comment by rochejul** [comment]
I close this issue due to no feedback

I hope the example works on your machine

Cheers
