### ISSUE TITLE
If the scenario get fails, the whole test suite execution get stopped

### ISSUE THREAD

**Issue by MohammedFazil** [rochejul/gulp-angular-protractor#28]
The protractor doesn't continue the next scenario, if the previous scenario get failed.
gulp-angular-protractor version 2.0.0

**Comment by rochejul** [comment]
Hi

Can you give me the output please ?

Have you tried with a previous version ?

Can you provide too your context:
- OS
- Node version
- NPM version
- gulp-angular-protractor version

Many thanks

**Comment by MohammedFazil** [comment]
@rochejul 

It throws the valid failure message, "unable to locate the element". After this error it stops the execution without continuing the next scenario.

Yes, In version 0.14 "session not created" message thrown after the server start. Tried with chrome browser.

OS- Windows : 8.1 pro
Node Version : 6.4.0
NPM Version  : 3.10.3
gulp-angular-protractor version : 2.0.0

**Comment by Milan-kumar** [comment]
This feature will be a great help, i tried following it consoles the error but doesn't start next spec execution:
.on('error', function (e) {
            console.log("specs: " + specs);
            console.log(e);
            process.exit(1);
            return new gutil.PluginError("ERROR", "Error", {showStack: true});
        })

**Comment by guan01** [comment]
Adding some background info,  I have 150 tests in a suite, was executing e2e, with some failed with previous framework v0.1.4
After upgraded to the latest v0.2.0 am getting this error which I might know what's the cause.
Error: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"

But, the test execution STOPPED.

OS- Windows : 10 pro
Node Version : 6.2.2
NPM Version : 3.9.5
gulp-angular-protractor version : 2.0.0

Thanks in advance, please comment and advise.

=============================================
[10:12:34] E/launcher - Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
[10:12:34] E/launcher - Error: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
    at C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\built\browser.js:273:23
    at ManagedPromise.invokeCallback_ (C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at asyncRun (C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2775:27)
    at C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: <anonymous>
    at Timeout.pollCondition [as _onTimeout] (C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2359:16)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
From: Task: <anonymous wait>
    at ControlFlow.wait (C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2352:17)
    at WebDriver.wait (C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:712:29)
    at ProtractorBrowser.to.(anonymous function) [as wait] (C:\htmlDev21\node_modules\gulp-angular-protractor\node_modules\protractor\built\browser.js:62:29)
    at World.<anonymous> (C:\htmlDev21\e2e\build\app\login\login.component.steps.js:435:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[10:12:34] E/launcher - Process exited with error code 199
[10:12:34] 10:12:34.738 INFO - Command request: shutDownSeleniumServer[, ] on session null

[10:12:34] 10:12:34.739 INFO - Shutdown command received

[10:12:34] 10:12:34.739 INFO - initiating shutdown

[10:12:34] gulp-angular-protractor - Webdriver standalone server is stopped
{ [Error: protractor exited with code 199]
  message: 'protractor exited with code 199',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-angular-protractor',
  __safety: { toString: [Function: bound ] } }
[10:12:34] 'e2e' errored after 21 min
[10:12:34] Error in plugin 'gulp-angular-protractor'
Message:
    protractor exited with code 199
[10:12:34] 10:12:34.740 INFO - Got result: OK on session null

[10:12:34] 10:12:34.892 INFO - Done: [execute script: return window.location.href;, []]

[10:12:35] [10:12:35] I/start - Selenium Standalone has exited with code 0

[10:12:35] gulp-angular-protractor - Webdriver standalone server will be closed

**Comment by rochejul** [comment]
see https://github.com/marcoturi/ionic2-boilerplate/issues/15
