### ISSUE TITLE
Update the dependency to protractor to its latest version 6.0.0

### ISSUE THREAD

**Issue by ghost** [rochejul/gulp-angular-protractor#52]
Right now the dependent protractor version is 4.0.11. However, the latest protractor version is 6.0.0. When will this depenedency be updated ?

**Comment by ghost** [comment]
It is causing chrome driver related errors when end to end tests are run:

 gulp e2e-test                   
[12:42:19] Requiring external module babel-register
[12:42:21] Using gulpfile ~/js-switch-energy/gulpfile.babel.js
[12:42:21] Starting 'e2e-test'...
[12:42:21] gulp-angular-protractor - The plugin is retrieved and will start soon
[12:42:21] gulp-angular-protractor - We will try to start and stop automatically the WebDriver server
[12:42:21] gulp-angular-protractor - The selenium address is: undefined
[12:42:21] gulp-angular-protractor - The selenium address used is: http://localhost:4444/wd/hub
[12:42:22] gulp-angular-protractor - We have the config file to the following path: /Users/nishanthgurung/js-switch-energy/test/protractor.conf.js
[12:42:22] gulp-angular-protractor - Webdriver standalone will be updated
[12:42:22] I/update - chromedriver: file exists /Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25mac64.zip
[12:42:22] I/update - chromedriver: unzipping chromedriver_2.25mac64.zip
[12:42:22] I/update - chromedriver: setting permissions to 0755 for /Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25
[12:42:22] I/update - chromedriver: v2.25 up to date
[12:42:22] I/update - selenium standalone: file exists /Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar
[12:42:22] I/update - selenium standalone: v2.53.1 up to date
[12:42:23] I/update - geckodriver: file exists /Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.11.1-macos.tar.gz
[12:42:23] I/update - geckodriver: unzipping geckodriver-v0.11.1-macos.tar.gz
[12:42:23] I/update - geckodriver: setting permissions to 0755 for /Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.11.1
[12:42:23] I/update - geckodriver: vv0.11.1 up to date
[12:42:28] gulp-angular-protractor - Webdriver standalone is updated
[12:42:28] gulp-angular-protractor - Webdriver standalone server will be started
[12:42:28] [12:42:28] I/start - java -Dwebdriver.chrome.driver=/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25 -Dwebdriver.gecko.driver=/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.11.1 -jar /Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar -port 4444

[12:42:28] [12:42:28] I/start - seleniumProcess.pid: 21750

[12:42:28] gulp-angular-protractor - Webdriver standalone server PID is detected:21750
[12:42:28] 12:42:28.893 INFO - Launching a standalone Selenium Server

[12:42:28] 12:42:28.921 INFO - Java: Oracle Corporation 25.201-b09

[12:42:28] 12:42:28.921 INFO - OS: Mac OS X 10.14.4 x86_64

[12:42:28] 12:42:28.930 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1

[12:42:28] 12:42:28.977 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC

[12:42:28] 12:42:28.978 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC

[12:42:28] 12:42:28.978 INFO - Driver class not found: com.opera.core.systems.OperaDriver

[12:42:28] 12:42:28.978 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered

[12:42:28] 12:42:28.980 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver

[12:42:28] 12:42:28.980 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered

[12:42:29] 12:42:29.028 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub

[12:42:29] 12:42:29.028 INFO - Selenium Server is up and running

[12:42:29] gulp-angular-protractor - Webdriver standalone server is started
[12:42:29] gulp-angular-protractor - We will run the Protractor engine
Report destination:   /Users/nishanthgurung/js-switch-energy/e2e-screenshots/failed-tests.html
(node:21751) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[12:42:29] I/local - Starting selenium standalone server...
[12:42:29] I/launcher - Running 1 instances of WebDriver
[12:42:29] I/local - Selenium standalone server started at http://10.54.32.190:52906/wd/hub
[12:43:40] E/launcher - unknown error: unrecognized Chrome version: HeadlessChrome/78.0.3882.0
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.14.4 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 252 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'OVO4471MB.local', ip: '10.54.32.190', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.chrome.ChromeDriver
[12:43:40] E/launcher - WebDriverError: unknown error: unrecognized Chrome version: HeadlessChrome/78.0.3882.0
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.14.4 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 252 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'OVO4471MB.local', ip: '10.54.32.190', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at Object.checkLegacyResponse (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/selenium-webdriver/builder.js:458:24)
    at Local.DriverProvider.getNewDriver (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/protractor/built/runner.js:197:43)
    at /Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/protractor/built/runner.js:276:30
    at _fulfilled (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/q/q.js:796:13)
    at /Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/q/q.js:604:44
    at runSingle (/Users/nishanthgurung/js-switch-energy/node_modules/gulp-angular-protractor/node_modules/q/q.js:137:13)
[12:43:40] E/launcher - Process exited with error code 199
[12:43:40] gulp-angular-protractor - We will stop the Protractor engine

**Comment by rochejul** [comment]
Hi @nishanthgurung 
As you can see, protractor is a devDependency: https://github.com/rochejul/gulp-angular-protractor/blob/master/package.json#L51

As explained here, you should declare which version you should use: https://github.com/rochejul/gulp-angular-protractor#side-dependencies

The goal was to let you the ability to use the protractor version (since peerDependency is not yet available)

Regards
