### ISSUE TITLE
Error: spawn webdriver-manager ENOENT after updating to 0.0.7

### ISSUE THREAD

**Issue by sharvit** [rochejul/gulp-angular-protractor#8]
After updating from version 0.0.6 to version 0.0.7 i cant run my tests again.

output after updating to version 0.0.7:

```
[16:51:34] Finished 'build' after 1.37 s
[16:51:34] Starting 'test:e2e:run-protractor-server'...
[16:51:34] Webserver started at http://localhost:8888
[16:51:34] gulp-angular-protractor - The plugin is retrieved and will start soon
[16:51:34] gulp-angular-protractor - We will try to start and stop automatically the WebDriver server
[16:51:34] gulp-angular-protractor - The selenium address is: undefined
[16:51:34] gulp-angular-protractor - The selenium address used is: http://localhost:4444/wd/hub
[16:51:34] gulp-angular-protractor - The selenium shutdown address used is: undefined
[16:51:34] gulp-angular-protractor - We have the config file to the following path: /Users/ramram/develop/angular/angular-full-seed/Users/ramram/develop/angular/angular-full-seed/e2e-tests/protractor.conf.js
[16:51:34] gulp-angular-protractor - Webdriver standalone will be updated
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.19/chromedriver_mac32.zip...
selenium-server-standalone-2.47.1.jar downloaded to /Users/ramram/develop/angular/angular-full-seed/node_modules/gulp-angular-protractor/node_modules/gulp-protractor/node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar
chromedriver_2.19.zip downloaded to /Users/ramram/develop/angular/angular-full-seed/node_modules/gulp-angular-protractor/node_modules/gulp-protractor/node_modules/protractor/selenium/chromedriver_2.19.zip
[16:52:42] gulp-angular-protractor - Webdriver standalone is updated
[16:52:42] gulp-angular-protractor - Webdriver standalone server will be started
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn webdriver-manager ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

after going back to version 0.0.6 everything is comming normal:

```
[16:41:52] Finished 'build' after 1.31 s
[16:41:52] Starting 'test:e2e:run-protractor-server'...
[16:41:52] Webserver started at http://localhost:8888
[16:41:52] gulp-angular-protractor - The plugin is retrieved and will start soon
[16:41:52] gulp-angular-protractor - We will try to start and stop automatically the WebDriver server
[16:41:52] gulp-angular-protractor - The selenium address is: undefined
[16:41:52] gulp-angular-protractor - The selenium address used is: http://localhost:4444/wd/hub
[16:41:52] gulp-angular-protractor - The selenium shutdown address used is: undefined
[16:41:52] gulp-angular-protractor - Webdriver standalone will be updated
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.20/chromedriver_mac32.zip...
chromedriver_2.20.zip downloaded to /Users/ramram/develop/angular/angular-full-seed/node_modules/protractor/selenium/chromedriver_2.20.zip
selenium-server-standalone-2.48.2.jar downloaded to /Users/ramram/develop/angular/angular-full-seed/node_modules/protractor/selenium/selenium-server-standalone-2.48.2.jar
[16:49:00] gulp-angular-protractor - Webdriver standalone is updated
[16:49:00] gulp-angular-protractor - Webdriver standalone server will be started
[16:49:00] seleniumProcess.pid: 5855

[16:49:01] 16:49:01.068 INFO - Launching a standalone Selenium Server

[16:49:01] Setting system property webdriver.chrome.driver to /Users/ramram/develop/angular/angular-full-seed/node_modules/protractor/selenium/chromedriver

[16:49:01] 16:49:01.115 INFO - Java: Oracle Corporation 25.45-b02

[16:49:01] 16:49:01.115 INFO - OS: Mac OS X 10.11.3 x86_64

[16:49:01] 16:49:01.129 INFO - v2.48.0, with Core v2.48.0. Built from revision 41bccdd

[16:49:01] 16:49:01.188 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC

[16:49:01] 16:49:01.189 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC

[16:49:01] 16:49:01.189 INFO - Driver class not found: com.opera.core.systems.OperaDriver

[16:49:01] 16:49:01.189 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered

[16:49:01] 16:49:01.285 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub

[16:49:01] 16:49:01.285 INFO - Selenium Server is up and running

[16:49:01] gulp-angular-protractor - Webdriver standalone server is started
[16:49:01] gulp-angular-protractor - We will run the Protractor engine
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.0.0.11:63020/wd/hub
Started
.......


7 specs, 0 failures
Finished in 15.815 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
[16:49:20] 16:49:20.356 INFO - Command request: shutDownSeleniumServer[, ] on session null

[16:49:20] 16:49:20.357 INFO - Shutdown command received

[16:49:20] gulp-angular-protractor - Webdriver standalone server is stopped
[16:49:20] Finished 'test:e2e:run-protractor-server' after 7.47 min
[16:49:20] Finished 'test:e2e' after 7.48 min
[16:49:20] Finished 'test' after 7.55 min
[16:49:20] 16:49:20.360 INFO - Got result: OK on session null
16:49:20.360 INFO - initiating shutdown

[16:49:20] 16:49:20.866 INFO - Shutting down...

[16:49:21] Selenium Standalone has exited with code 0

[16:49:21] gulp-angular-protractor - Webdriver standalone server will be closed
```

anything i can do?

Thanks :+1:

**Comment by rochejul** [comment]
Hi

Are you on a windows platform ? If so, I've got a similar issue: http://stackoverflow.com/questions/28624686/get-spawn-cmd-enoent-when-try-to-build-cordova-application-event-js85

We have this kind of error when the "c:/windows/system32' is not into the PATH.

This is a well knowed issue on nodejs windows version, and it occurs when we specify the "cwd" option for child_process.exec or child_process.spwan functions

Can you check that please ?

Many thanks

**Comment by sharvit** [comment]
i am using osx 10.11.13

i tried to export JAVA_PATH=...
i tried it with v7 and v8

**Comment by sharvit** [comment]
it is also weird that v0.0.7 donloading selenium-server-standalone-2.47.1.jar
and v0.0.6 downloading selenium-server-standalone-2.48.2.jar

Thanks :)

**Comment by rochejul** [comment]
Hi

Can you try to do the following command:
rm -rf ~/.npm

Plus, can you verify if you have a PATH variable ?

Many thanks

**Comment by sharvit** [comment]
Hi,

I tried the following:

```
rm -rf ~/.npm
rm -rf ~/.nvm/versions
rm -rf node_modules
```

testing output is still the same :(

PATH is looking good

```
echo $PATH
```

bins, npm, nvm, rvm anything their...
something about java should be their? because it is not...

Thanks

**Comment by rochejul** [comment]
Maybe

Can ou test it ?

Many thanks

**Comment by sharvit** [comment]
seems that PATH should include nothing about JAVA
i found a few things about JAVA_HOME but it seems that this variable do not affect anything.

I also do not understand why it is downloading
`selenium-server-standalone-2.47.1.jar`
and not `selenium-server-standalone-2.48.2.jar`
like v0.0.6 do

**Comment by rochejul** [comment]
Maybe this is an evolution from gulp-protractor (we use the 1.0.0 version)

Can you run with the verbose mode ? Maybe we will have more details ?

Many thanks

**Comment by gruppjo** [comment]
I get the same error. How do I run in verbose mode?

**Comment by rochejul** [comment]
Hi

you have to simply add "--verbose" at the end of the gulp command

**Comment by rochejul** [comment]
Hi,

Can you try to run this code onto your system and tell me what is the output ? If you have the same error, there is a problem on your system (for example, on windows, if the system32 folder is not into the PATH, we have the same issue):

``` javascript
'use strict';

var childProcess = require('child_process');

function _interceptLogData(data) {
    var dataString = data.toString();
    console.log(dataString);
}

var command = childProcess.spawn('ls', ['-la']);

command.once('close', function (err) {
    if (err) {
        console.error(err);

    } else {
        console.log('Finished !');
    }
});

command.stderr.on('data', _interceptLogData);
command.stdout.on('data', _interceptLogData);
```

Cheers

**Comment by AaronBuxbaum** [comment]
+1 on this issue. I'm running my tests fine on my windows machine, but I get the error when I run it over Sauce Labs.

**Comment by rochejul** [comment]
Hi

When you downgade to 0.0.6, it works fine ?

Many thanks for your feebback

Cheers

**Comment by AaronBuxbaum** [comment]
@rochejul Yup! This bug was introduced in 0.0.7.

**Comment by rochejul** [comment]
It works fine on my ubuntu and windows stations.

What is your configuration  ?

**Comment by AaronBuxbaum** [comment]
I get this bug when I'm running e2e tests on my deployment pipeline (TravisCI -> Sauce Labs), so I'm not really aware of the configurations. It might be worth creating your own instances of these and trying it yourself to see -- my guess is that your machine might have something installed that aren't on those machines.

All I do know is that Sauce runs on Linux and Chrome 48.

**Comment by rochejul** [comment]
Can you run the previous code on travis/ saucelabs please  ? 

If an error is raised, that means this is probably a NodeJs problem.

Many thanks

**Comment by AaronBuxbaum** [comment]
0.0.7 does not work; 0.0.6 works fine. I get the same `spawn webdriver-manager ENOENT` error as OP.

**Comment by rochejul** [comment]
What is the version of Java ?

Do you use at least JDK 1.7 ?

**Comment by rochejul** [comment]
Can you try out the 0.1.0 version please ?

Many thanks

**Comment by AaronBuxbaum** [comment]
No difference on master (0.1.0); not sure about Java version since it's the Sauce Labs machine. I imagine it's on a relatively recent JDK, but I don't know.

**Comment by elgervb** [comment]
Looks like I'm having the same problem as well when using version 0.0.7.

Take a look at my Travis configuration:
https://travis-ci.org/elgervb/skeletonSPA/builds/113420806

Build system info is at the top of the log of each build job.
Java version is 1.7.0_76. 

Will revert my project [skeletonSPA ](https://github.com/elgervb/skeletonSPA)to version 0.0.6 for now

**Comment by rochejul** [comment]
@elgervb Can you check if the version 0.1.0 works please ?

Many thanks

**Comment by elgervb** [comment]
@rochejul looks like 0.1.0 is working ;-)

Do you need to publish it on npm? Latest release on npm.com is 0.7.0...

**Comment by rochejul** [comment]
Weird the publication seems to have failed

I will publish as soon as possible

Cheers

**Comment by elgervb** [comment]
Tnx @rochejul! I'll update when publication succeeded

**Comment by rochejul** [comment]
The 0.1.1 version was published

Many thanks, I closed the issue

**Comment by dakolech** [comment]
The 0.1.1 version is not solving the issue. Same error: 

```
Error: spawn webdriver-manager ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

OS X 10.11.3

**Comment by rochejul** [comment]
Hi @dakolech

Have you check the java version and PATH variable  ? 

Can you give more details on your node, npm, java versions  ? 

Many thanks

**Comment by AaronBuxbaum** [comment]
I still get the same error in my Sauce build as well.

**Comment by dakolech** [comment]
java version: 1.7.0_79
node: v4.3.2
npm: 2.14.12

There is a `export JAVA_HOME=$(/usr/libexec/java_home)` in .zshrc.

**Comment by rochejul** [comment]
Can you try this script and give me the output ? 

``` js
'use strict';

var childProcess = require('child_process');

function _interceptLogData(data) {
    var dataString = data.toString();
    console.log(dataString);
}

var command = childProcess.spawn('ls', ['-la']);

command.once('close', function (err) {
    if (err) {
        console.error(err);

    } else {
        console.log('Finished !');
    }
});

command.stderr.on('data', _interceptLogData);
command.stdout.on('data', _interceptLogData);
```

Thanks

**Comment by dakolech** [comment]
where should I run it? If i run it in the main app folder, then the output is the same as ls -la.

**Comment by rochejul** [comment]
You can run it anywhere :  this is a nodejs test
Cheers

**Comment by dakolech** [comment]
```
total 200
drwxr-xr-x  31 dako  staff  1054  7 mar 16:42 .
drwxr-xr-x  27 dako  staff   918  2 mar 09:55 ..
-rw-r--r--@  1 dako  staff  6148  8 lut 15:21 .DS_Store
-rw-r--r--   1 dako  staff    28  9 lut 16:08 .babelrc
-rw-r--r--   1 dako  staff    16  9 lut 16:08 .bash_profile
-rw-r--r--   1 dako  staff    16  9 lut 16:08 .bashrc
-rw-r--r--   1 dako  staff    62  9 lut 16:08 .bowerrc
-rw-r--r--   1 dako  staff   414  9 lut 16:08 .editorconfig
-rw-r--r--   1 dako  staff   858  7 mar 11:24 .eslintrc.yml
-rw-r--r--   1 dako  staff   245  2 mar 09:54 .gitignore
-rw-r--r--   1 dako  staff  1447  9 lut 16:08 .jade-lint.json
-rw-r--r--   1 dako  staff     6  7 mar 11:24 .node-version
-rw-r--r--   1 dako  staff  4644  9 lut 16:08 .scss-lint.yml
-rw-r--r--   1 dako  staff    16  9 lut 16:08 .zshrc
-rw-r--r--   1 dako  staff   527  4 mar 14:33 README.md
drwxr-xr-x   8 dako  staff   272  1 mar 10:25 app
drwxr-xr-x   6 dako  staff   204  9 lut 16:08 assets
-rw-r--r--   1 dako  staff   966  1 mar 10:25 bower.json
drwxr-xr-x  25 dako  staff   850 23 lut 16:06 bower_components
drwxr-xr-x   3 dako  staff   102  4 lut 15:54 coverage
drwxr-xr-x   8 dako  staff   272  7 mar 11:24 gulp
-rw-r--r--   1 dako  staff  7478  7 mar 11:24 gulpfile.js
-rw-r--r--   1 dako  staff  2622  4 mar 14:33 karma.config.js
drwxr-xr-x   4 dako  staff   136 10 lut 15:25 locales
-rw-r--r--   1 dako  staff   449  7 mar 16:42 new.js
drwxr-xr-x  73 dako  staff  2482  7 mar 14:50 node_modules
-rw-r--r--   1 dako  staff  2243  7 mar 14:59 package.json
-rw-r--r--   1 dako  staff  6683  7 mar 14:36 paths.config.js
-rw-r--r--   1 dako  staff   754  4 mar 14:33 protractor.config.js
drwxr-xr-x   4 dako  staff   136  9 lut 16:08 test
-rw-r--r--   1 dako  staff   508  4 mar 14:33 webpack.config.js

Finished !
```

**Comment by pgom** [comment]
I also get the same error on both `0.0.7` and `0.1.1` version running on OSX 10.11.4 and:
- java: 1.8.0_65
- node: 5.1.0
- npm: 3.8.5

**Comment by lrkwz** [comment]
This solved for me:

```
 npm rm --global gulp
 sudo npm rm --global gulp
 sudo npm install --global gulp-cli
```

**Comment by red2678** [comment]
I am still getting this error on both 0.0.7 and 0.1.1. I went back to 0.0.6 and all is well.
- java: 1.8.0_65
- node: 4.4.7
- npm: 3.10.3

**Comment by jmmclean** [comment]
This issue exists with v0.3.0. Downgrading to version 0.0.6 worked for me.

**Comment by maikdiepenbroek** [comment]
Same here!
